/*
 * This  code modified from sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/stat.h>
#include <unistd.h>
#include <pwd.h>
#include <rpc/rpc.h>
#include <pwd.h>

#include "ssnfs.h"

CLIENT *clnt;

void
ssnfsprog_1(char *host)
{
clnt = clnt_create (host, SSNFSPROG, SSNFSVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
}

int Open(char *filename_to_open){
  open_output  *result_1;
  open_input  open_file_1_arg;
  strcpy(open_file_1_arg.user_name, (getpwuid(getuid()))->pw_name);
  strcpy(open_file_1_arg.file_name,filename_to_open);
  result_1 = open_file_1(&open_file_1_arg, clnt);
	if (result_1 == (open_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf (" File name is %s\n", (*result_1).out_msg.out_msg_val);
	return ( (*result_1).fd);
}

/*

	read_output  *result_2;
	read_input  read_file_1_arg;
	write_output  *result_3;
	write_input  write_file_1_arg;
	list_output  *result_4;
	list_input  list_files_1_arg;
	delete_output  *result_5;
	delete_input  delete_file_1_arg;
	close_output  *result_6;
	close_input  close_file_1_arg;
        seek_output * result_7;
        seek_input seek_position_1_arg;

	
	result_2 = read_file_1(&read_file_1_arg, clnt);
	if (result_2 == (read_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = write_file_1(&write_file_1_arg, clnt);
	if (result_3 == (write_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = list_files_1(&list_files_1_arg, clnt);
	if (result_4 == (list_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = delete_file_1(&delete_file_1_arg, clnt);
	if (result_5 == (delete_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = close_file_1(&close_file_1_arg, clnt);
	if (result_6 == (close_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
       	result_7 = seek_position_1(&seek_position_1_arg, clnt);
	if (result_7 == (seek_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	

*/

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ssnfsprog_1 (host);
	int fd;
	fd=Open("MyFile");
	printf("File descripter retuned is %d \n",fd);
	/*
int i,j;
int fd1,fd2;
char buffer[100];
fd1=Open("File1"); // opens the file "File1"
for (i=0; i< 20;i++){
  Write(fd1,  "This is a test program for cs570 assignment 4", 15);
}
Close(fd1);
fd2=Open("File1");
for (j=0; j< 20;j++){
    Read(fd2, buffer, 10);  
    printf("%s\n",buffer);
}
Seek (fd2,40);
Read(fd2, buffer, 20);
printf("%s\n",buffer);
Close(fd2);
Delete("File1");
List();
	 */
	
exit (0);
}
