/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ssnfs.h"


void
ssnfsprog_1(char *host)
{
	CLIENT *clnt;
	open_output  *result_1;
	open_input  open_file_1_arg;
	read_output  *result_2;
	read_input  read_file_1_arg;
	write_output  *result_3;
	write_input  write_file_1_arg;
	list_output  *result_4;
	list_input  list_files_1_arg;
	delete_output  *result_5;
	delete_input  delete_file_1_arg;
	close_output  *result_6;
	close_input  close_file_1_arg;
	seek_output  *result_7;
	seek_input  seek_position_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SSNFSPROG, SSNFSVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = open_file_1(&open_file_1_arg, clnt);
	if (result_1 == (open_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = read_file_1(&read_file_1_arg, clnt);
	if (result_2 == (read_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = write_file_1(&write_file_1_arg, clnt);
	if (result_3 == (write_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = list_files_1(&list_files_1_arg, clnt);
	if (result_4 == (list_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = delete_file_1(&delete_file_1_arg, clnt);
	if (result_5 == (delete_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = close_file_1(&close_file_1_arg, clnt);
	if (result_6 == (close_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = seek_position_1(&seek_position_1_arg, clnt);
	if (result_7 == (seek_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ssnfsprog_1 (host);
exit (0);
}
